### ISSUE TITLE
dockerhub pull fails

### ISSUE THREAD

**Issue by bayesfactor** [nwchemgit/nwchem-dockerfiles#1]
From https://hub.docker.com/r/pnnl/nwchem I tried the instruction: docker pull pnnl/nwchem

The error I got was:
Error response from daemon: manifest for pnnl/nwchem not found

**Comment by edoapra** [comment]
The docker images of this repository are under https://hub.docker.com/r/nwchemorg
Please try the following command
```
docker pull nwchemorg/nwchem-681.fedora.sockets
```
