### ISSUE TITLE
nwpw_input is not in this build of NWChem

### ISSUE THREAD

**Issue by RiccardoRomagnoli** [nwchemgit/nwchem-dockerfiles#102]
Hello,

I'm trying to use the nwpw method with the nwchem docker image version 7.2 . When using nwpw method seems like the module is not present in the build (output: nwpw_input is not in this build of NWChem) despite the fact that in the dockerfile I see NWCHEM_MODULES=all python

Why is that?
How can I successfully use nwpw with a docker image of NWChem?

**Comment by edoapra** [comment]
@RiccardoRomagnoli thank your for filing this issue.
The new 7.2.0 image does contain the nwpw module.
```
ghcr.io/nwchemgit/nwchem-720:amd64@sha256:c848376df8f486eae60e646d58cd46b9a78ae9ffd14ae922ea01aac045d1907b
```

**Comment by RiccardoRomagnoli** [comment]
Thanks, now working fine!
