### ISSUE TITLE
 dplot_input is not in this build of NWChem

### ISSUE THREAD

**Issue by chenxin199261** [nwchemgit/nwchem-dockerfiles#123]
Hello, 

I want to use dplot to plot the electron density. The input file is, 

```
start n2
geometry
  n  0 0   0.53879155
  n  0 0  -0.53879155
end
basis;  n library cc-pvdz;end
scf
vectors  output n2.movecs
end
dplot
  TITLE HOMO
  vectors n2.movecs
   LimitXYZ
 -3.0 3.0 10
 -3.0 3.0 10
 -3.0  3.0  10
  spin total
  gaussian
  output chargedensity.cube
end
task scf
task dplot
```

My docker command is:

```
docker run --shm-size $mem  -u `id -u`  -e OMP_NUM_THREADS=12  --rm  --entrypoint='mpirun' -v $PWD:/data ghcr.io/nwchemgit/nwchem-dev/amd64 -np 4 nwchem input.nw
```
 
**REPOSITORY** : ghcr.io/nwchemgit/nwchem-dev/amd64   
**TAG** : latest            
**IMAGE ID** : ee871dffb7f2

There is a complain in the output file that,

```
 ------------------------------------------------------------------------
 dplot_input is not in this build of NWChem                   0
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
  current input line : 
    10: dplot
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
 A feature requested has not yet been implemented

 ------------------------------------------------------------------------

```

Is dplot module is removed for compact docker images ? How can I recover it?

Yours,

**Comment by edoapra** [comment]
Please use the current dev image as in the example below (and stick to `OMP_NUM_THREADS=1`, unless you want to slow down NWChem!)
```
docker run --shm-size 256mb  -u `id -u`  -e OMP_NUM_THREADS=1  --rm  --entrypoint='mpirun' -v $PWD:/data ghcr.io/nwchemgit/nwchem-dev -np 4 nwchem /data/input.nw
```
https://nwchemgit.github.io/Containers.html

**Comment by chenxin199261** [comment]
> Please use the current dev image as in the example below (and stick to `OMP_NUM_THREADS=1`, unless you want to slow down NWChem!)
> 
> ```
> docker run --shm-size 256mb  -u `id -u`  -e OMP_NUM_THREADS=1  --rm  --entrypoint='mpirun' -v $PWD:/data ghcr.io/nwchemgit/nwchem-dev -np 4 nwchem /data/input.nw
> ```
> 
> https://nwchemgit.github.io/Containers.html

Thank you so much for your quick reply, problem solved! And also thanks your advice on OpenMP setting.
