### ISSUE TITLE
small

### ISSUE THREAD

**Issue by bayesfactor** [nwchemgit/nwchem-dockerfiles#2]
small Dockerfile Line 36: curl -SL http://www.nwchem-sw.org/images/Nwchem-6.8.revision29612-srconly.2017-11-07.tar.bz2
produces an issue:
 curl -SL http://www.nwchem-sw.org/images/Nwchem-6.8.revision29612-srconly.2017-11-07.tar.bz
<html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult with your administrator.<br><br>Your support ID is: 16164719067947417698<br><br><a href='javascript:history.back();'>[Go Back]</a></body></html>

**Comment by edoapra** [comment]
@bayesfactor the dockerfile you are trying to use is woefully out of date.
Please use nwchem-681.fedora.sockets, instead
https://github.com/nwchemgit/nwchem-dockerfiles/tree/master/nwchem-681.fedora.sockets
