### ISSUE TITLE
Is amber gromacs downloaded as a dependency along with NWChem?

### ISSUE THREAD

**Issue by anubhav0fnu** [nwchemgit/nwchem-dockerfiles#8]
[This one?](http://www.gromacs.org/Documentation_of_outdated_versions/Terminology/Force_Fields/AMBER?highlight=generates)
I'm currently using  `nwchem-6.8.1`, also could you please point to me where you download the AMBER dependencies?
in Dockerfile or part of the `nwchem-6.8.1` source code would be helpful? Also which version of GROMACS you're using, how to obtain version?
@nwchemgit @bayesfactor @edoapra @ajaypanyala

**Comment by edoapra** [comment]
These repository contains just  NWChem docker images. 
I have never used either AMBER or GROMACS.
You might want to contact the authors of the paper describing the NWChem/AMBER interface, instead
[https://doi.org/10.1002/jcc.24804](https://doi.org/10.1002/jcc.24804)

**Comment by anubhav0fnu** [comment]
> These repository contains just NWChem docker images.
> I have never used either AMBER or GROMACS.
> You might want to contact the authors of the paper describing the NWChem/AMBER interface, instead
> https://doi.org/10.1002/jcc.24804

@edoapra , thank you so much.
There are so many dockerfiles in this repo, could the maintainers of the `nwchemgit/nwchem-dockerfiles` repo write a piece of sufficient information on the main README.md as in what each Dockerfile deliveres? It would be very helpful for other developers.

On a quick search `NMchecm` on docker hub, it brings in [42 different images](https://hub.docker.com/search?q=nwchem&type=image) and a very few have good README.md to as a starter.

**Comment by edoapra** [comment]
@anubhav0fnu I am not sure what is `NMchecm` that you are referring to ...

Anyhow, probably the most portable and complete docker image can be built with what is in
https://github.com/nwchemgit/nwchem-dockerfiles/tree/master/nwchem-700.mpipr

The corresponding image is 
https://hub.docker.com/repository/docker/nwchemorg/nwchem-700.mpipr

**Comment by anubhav0fnu** [comment]
> not sure what is

I'm sorry,my bad, that was a typo `NMchem` I was taking about.
